In [1]:
import pandas as pd
from pathlib import Path

data_path = Path(r"C:\Users\bilal\Desktop\AnalyticsVidhya_Assessment\data\archive")

print("Files:")
for file in data_path.iterdir():
    print(file.name)

Files:
Answers.csv
Questions.csv
Tags.csv

In [2]:
import pandas as pd

questions = pd.read_csv(
    r"C:\Users\bilal\Desktop\AnalyticsVidhya_Assessment\data\archive\Questions.csv",
    nrows=5
)

answers = pd.read_csv(
    r"C:\Users\bilal\Desktop\AnalyticsVidhya_Assessment\data\archive\Answers.csv",
    nrows=5
)

tags = pd.read_csv(
    r"C:\Users\bilal\Desktop\AnalyticsVidhya_Assessment\data\archive\Tags.csv",
    nrows=5
)

print("QUESTIONS COLUMNS")
print(questions.columns.tolist())

print("\nANSWERS COLUMNS")
print(answers.columns.tolist())

print("\nTAGS COLUMNS")
print(tags.columns.tolist())

QUESTIONS COLUMNS
['Id', 'OwnerUserId', 'CreationDate', 'Score', 'Title', 'Body']

ANSWERS COLUMNS
['Id', 'OwnerUserId', 'CreationDate', 'ParentId', 'Score', 'Body']

TAGS COLUMNS
['Id', 'Tag']

In [3]:
display(questions.head(1))
display(answers.head(1))
display(tags.head(1))

,Id,OwnerUserId,CreationDate,Score,Title,Body
0,469,147,2008-08-02T15:11:16Z,21,How can I find the full path to a font from it...,<p>I am using the Photoshop's javascript API t...

,Id,OwnerUserId,CreationDate,ParentId,Score,Body
0,497,50,2008-08-02T16:56:53Z,469,4,<p>open up a terminal (Applications-&gt;Utilit...

    Id     Tag
0  469  python

In [4]:
questions = pd.read_csv(
    r"C:\Users\bilal\Desktop\AnalyticsVidhya_Assessment\data\archive\Questions.csv",
    nrows=1000
)

answers = pd.read_csv(
    r"C:\Users\bilal\Desktop\AnalyticsVidhya_Assessment\data\archive\Answers.csv",
    nrows=1000
)

print("Questions:", questions.shape)
print("Answers:", answers.shape)

print("\nQuestion sample:")
display(questions.head())

print("\nAnswer sample:")
display(answers.head())

Questions: (1000, 6)
Answers: (1000, 6)

Question sample:

,Id,OwnerUserId,CreationDate,Score,Title,Body
0,469,147.0,2008-08-02T15:11:16Z,21,How can I find the full path to a font from it...,<p>I am using the Photoshop's javascript API t...
1,502,147.0,2008-08-02T17:01:58Z,27,Get a preview JPEG of a PDF on Windows?,<p>I have a cross-platform (Python) applicatio...
2,535,154.0,2008-08-02T18:43:54Z,40,Continuous Integration System for a Python Cod...,<p>I'm starting work on a hobby project with a...
3,594,116.0,2008-08-03T01:15:08Z,25,cx_Oracle: How do I iterate over a result set?,<p>There are several ways to iterate over a re...
4,683,199.0,2008-08-03T13:19:16Z,28,Using 'in' to match an attribute of Python obj...,<p>I don't remember whether I was dreaming or ...

Answer sample:

,Id,OwnerUserId,CreationDate,ParentId,Score,Body
0,497,50.0,2008-08-02T16:56:53Z,469,4,<p>open up a terminal (Applications-&gt;Utilit...
1,518,153.0,2008-08-02T17:42:28Z,469,2,<p>I haven't been able to find anything that d...
2,536,161.0,2008-08-02T18:49:07Z,502,9,<p>You can use ImageMagick's convert utility f...
3,538,156.0,2008-08-02T18:56:56Z,535,23,<p>One possibility is Hudson. It's written in...
4,541,157.0,2008-08-02T19:06:40Z,535,20,"<p>We run <a href=""http://buildbot.net/trac"">B..."

In [5]:
answers.groupby("ParentId").size().sort_values(ascending=False).head(10)

ParentId
63086    24
51553    10
60649    10
43775    10
56820     9
42034     8
61151     8
77086     8
74430     8
5313      8
dtype: int64

In [6]:
from bs4 import BeautifulSoup

def clean_html(text):
    return BeautifulSoup(str(text), "html.parser").get_text(" ")

In [8]:
questions = pd.read_csv(
    r"C:\Users\bilal\Desktop\AnalyticsVidhya_Assessment\data\archive\Questions.csv",
    encoding="latin1",
    nrows=5
)

print(questions.head())

    Id  OwnerUserId          CreationDate  Score  \
0  469          147  2008-08-02T15:11:16Z     21
1  502          147  2008-08-02T17:01:58Z     27
2  535          154  2008-08-02T18:43:54Z     40
3  594          116  2008-08-03T01:15:08Z     25
4  683          199  2008-08-03T13:19:16Z     28

                                               Title  \
0  How can I find the full path to a font from it...
1            Get a preview JPEG of a PDF on Windows?
2  Continuous Integration System for a Python Cod...
3     cx_Oracle: How do I iterate over a result set?
4  Using 'in' to match an attribute of Python obj...

                                                Body
0  <p>I am using the Photoshop's javascript API t...
1  <p>I have a cross-platform (Python) applicatio...
2  <p>I'm starting work on a hobby project with a...
3  <p>There are several ways to iterate over a re...
4  <p>I don't remember whether I was dreaming or ...

In [9]:
answers = pd.read_csv(
    r"C:\Users\bilal\Desktop\AnalyticsVidhya_Assessment\data\archive\Answers.csv",
    encoding="latin1",
    usecols=["Id"],
)

print("Answers:", len(answers))

Answers: 987122

In [10]:
tags = pd.read_csv(
    r"C:\Users\bilal\Desktop\AnalyticsVidhya_Assessment\data\archive\Tags.csv",
    encoding="latin1",
    usecols=["Id"],
)

print("Tags:", len(tags))

Tags: 1885078

In [11]:
questions = pd.read_csv(
    r"C:\Users\bilal\Desktop\AnalyticsVidhya_Assessment\data\archive\Questions.csv",
    encoding="latin1",
    usecols=["Id"]
)

print(len(questions))

607282